import time
from picarx import Picarx
from robot_hat import Music,TTS

music = Music()
tts = TTS()
px = Picarx()

def main():
    music.music_set_volume(20)
    tts.lang("en-US")

    tts.say("3")
    tts.say("2")
    tts.say("1")
    tts.say("DANCE!")
    music.music_play('../musics/slow-trail-Ahjay_Stelino.mp3')
    for i in range(3):
        px.set_dir_servo_angle(30)
        px.set_cam_pan_angle(30)
        px.set_cam_tilt_angle(30)
        time.sleep(0.5)
        px.set_dir_servo_angle(-30)
        px.set_cam_pan_angle(-30)
        px.set_cam_tilt_angle(-30)
        time.sleep(0.5)
        px.set_dir_servo_angle(0)
        px.set_cam_pan_angle(0)
        px.set_cam_tilt_angle(0)
        time.sleep(0.5)
        px.set_dir_servo_angle(-15)
        px.backward(15)
        time.sleep(0.5)
        px.backward(0)
        px.set_dir_servo_angle(15)
        px.forward(15)
        time.sleep(0.5)
        px.forward(0)
        px.set_dir_servo_angle(-30)
        px.set_cam_pan_angle(30)
        px.set_cam_tilt_angle(-30)
        time.sleep(0.5)
        px.set_dir_servo_angle(30)
        px.set_cam_pan_angle(-30)
        px.set_cam_tilt_angle(30)
        time.sleep(0.5)
        px.set_dir_servo_angle(0)
        px.set_cam_pan_angle(0)
        px.set_cam_tilt_angle(0)
        time.sleep(0.5)
    music.music_stop()
    tts.say("Woohoo!")

if __name__ == "__main__": main()
